# Generated by Django 4.1.5 on 2023-01-29 17:12

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('avatar', models.URLField()),
                ('hall', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('upi_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('game_name', models.CharField(max_length=100)),
                ('info_type', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('INFO', 'Info'), ('CHAT', 'Chat'), ('VIDEO', 'Video')], default='VIDEO', max_length=10), default=['INFO', 'CHAT', 'VIDEO'], size=None)),
                ('group_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('state', models.JSONField(default=dict)),
                ('actions', models.JSONField(default=dict)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='api.player')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='server', to='api.player')),
            ],
        ),
    ]
