# Generated by Django 4.1.5 on 2023-03-11 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='gender',
            field=models.CharField(default='M', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='upi_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
